AWSTemplateFormatVersion: '2010-09-09'
Description: 'Costra AWS Billing Connection - Grants Costra read-only access to AWS billing and cost data'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Connection Information
      Parameters:
      - ConnectionName
      - CostraAccountId
    - Label:
        default: Security
      Parameters:
      - ExternalId
    ParameterLabels:
      ConnectionName:
        default: 'Connection Name (descriptive alias for this AWS account)'
      CostraAccountId:
        default: 'Costra AWS Account ID'
      ExternalId:
        default: 'External ID (for secure cross-account access)'

Parameters:
  ConnectionName:
    Type: String
    Description: 'Descriptive name for this connection (used to identify your account in Costra)'
    Default: 'costra-billing-connection'
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must be lowercase alphanumeric with hyphens only (3-64 characters)'
    MinLength: 3
    MaxLength: 64
  
  CostraAccountId:
    Type: String
    Description: 'Costra AWS Account ID (provided by Costra)'
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'
  
  ExternalId:
    Type: String
    Description: 'External ID for secure cross-account access (provided by Costra)'
    MinLength: 16
    MaxLength: 1224
    NoEcho: true
    AllowedPattern: '^[a-zA-Z0-9+/=._-]+$'
    ConstraintDescription: 'External ID must contain only alphanumeric characters and safe special characters'

Conditions:
  HasConnectionName: !Not [!Equals [!Ref ConnectionName, '']]

Resources:
  CostraAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If
        - HasConnectionName
        - !Sub 'CostraAccessRole-${ConnectionName}'
        - !Sub 'CostraAccessRole-${AWS::StackName}'
      Description: !Sub 'Role for Costra to access AWS billing and cost data for ${ConnectionName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCostraAssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${CostraAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing
      Policies:
        - PolicyName: CostraCostExplorerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CostExplorerAccess
                Effect: Allow
                Action:
                  - 'ce:GetCostAndUsage'
                  - 'ce:GetCostAndUsageWithResources'
                  - 'ce:GetDimensionValues'
                  - 'ce:GetReservationCoverage'
                  - 'ce:GetReservationPurchaseRecommendation'
                  - 'ce:GetReservationUtilization'
                  - 'ce:GetRightsizingRecommendation'
                  - 'ce:GetSavingsPlansCoverage'
                  - 'ce:GetSavingsPlansPurchaseRecommendation'
                  - 'ce:GetSavingsPlansUtilization'
                  - 'ce:GetUsageReport'
                  - 'ce:ListCostCategoryDefinitions'
                  - 'ce:DescribeCostCategoryDefinition'
                Resource: '*'
              - Sid: CostAndUsageReportsAccess
                Effect: Allow
                Action:
                  - 'cur:DescribeReportDefinitions'
                  - 'cur:PutReportDefinition'
                  - 'cur:ModifyReportDefinition'
                  - 'cur:DeleteReportDefinition'
                Resource: '*'
              - Sid: OrganizationsAccess
                Effect: Allow
                Action:
                  - 'organizations:DescribeOrganization'
                  - 'organizations:DescribeAccount'
                  - 'organizations:DescribeOrganizationalUnit'
                  - 'organizations:ListAccounts'
                  - 'organizations:ListOrganizationalUnitsForParent'
                  - 'organizations:ListParents'
                  - 'organizations:ListRoots'
                  - 'organizations:ListTagsForResource'
                Resource: '*'
              - Sid: CloudWatchMetricsAccess
                Effect: Allow
                Action:
                  - 'cloudwatch:GetMetricData'
                  - 'cloudwatch:ListMetrics'
                  - 'cloudwatch:GetMetricStatistics'
                Resource: '*'
              - Sid: TaggingAccess
                Effect: Allow
                Action:
                  - 'tag:GetResources'
                  - 'tag:GetTagKeys'
                  - 'tag:GetTagValues'
                Resource: '*'
      MaxSessionDuration: 3600
      Tags:
        - Key: ManagedBy
          Value: Costra
        - Key: Purpose
          Value: BillingDataAccess
        - Key: ConnectionName
          Value: !If
            - HasConnectionName
            - !Ref ConnectionName
            - !Ref AWS::StackName
        - Key: CreatedBy
          Value: CloudFormation
        - Key: CostraAccountId
          Value: !Ref CostraAccountId

Outputs:
  RoleArn:
    Description: 'ARN of the IAM role that Costra will use to access your AWS account'
    Value: !GetAtt CostraAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  ExternalId:
    Description: 'External ID used for secure access (save this for reference)'
    Value: !Ref ExternalId
    Export:
      Name: !Sub '${AWS::StackName}-ExternalId'
  
  ConnectionName:
    Description: 'Name of this connection'
    Value: !If
      - HasConnectionName
      - !Ref ConnectionName
      - !Ref AWS::StackName
    Export:
      Name: !Sub '${AWS::StackName}-ConnectionName'
  
  AccountId:
    Description: 'AWS Account ID where this stack is deployed'
    Value: !Ref AWS::AccountId
    Export:
      Name: !Sub '${AWS::StackName}-AccountId'
  
  StackName:
    Description: 'CloudFormation stack name'
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub '${AWS::StackName}-StackName'
  
  Region:
    Description: 'AWS Region where this stack is deployed'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'
